### ISSUE TITLE
TODO: Items before release

### ISSUE THREAD

**Issue by mjc4wilton** [mjc4wilton/jsoc_ew#3]
### ACRE
- [ ] Create ACRE-specific jamming radio
- [ ] Transition functions to new jammer
- [ ] Ensure the jamming tone works correctly

### Base
- [ ] Create dialog for hacking to simulate desktop or CLI environment
- [ ] Rework ACE interactions to make it more intuitive in MP environments
- [ ] See if its possible to adjust the IED jamming ace actions to not overlap text when using list ace-interaction mode

### Contact
- [ ] Create a tracker which can be followed using the spectrum device
- [ ] Create an API for the spectrum device sources
- [ ] Fix CBA notification when player does not have a 152 not appearing on-time
- [ ] Allow the spectrum device's frequency range to be adjusted /  zoom in / zoom out
